apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.name }}
spec:
  selector: {{ include "common.mongo" . | nindent 4 }}
  ports:
    - port: {{ .Values.mongo.port }}
      targetPort: {{ .Values.mongo.targetPort }}