apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: student-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
        - path: /?(.*)
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.client.name }}
              port:
                number: {{ .Values.client.port }}
        - path: /api/?(.*)
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.api.name}}
              port:
                number: {{ .Values.api.port }}


