apiVersion: v1
kind: Service
metadata:
  name: student-app-api
spec:
  selector: {{ include "common.api" . | nindent 4 }}
  ports:
    - port: {{ .Values.api.port }}
      protocol: TCP
      targetPort:  {{ .Values.api.targetPort }}
